import asyncio
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

# Ensure root is in path
ROOT = Path(__file__).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from backend.agents.orchestrator import AgentOrchestrator
from backend.agents.writer_agent import WriterAgent

async def test_all_report_types():
    print("\n=======================================================")
    print("TESTING 4-TIER REPORT TYPE EXECUTION MODES")
    print("=======================================================")

    orchestrator = AgentOrchestrator()

    # -------------------------------------------------------------------------
    # TEST 1: SUMMARY MODE (Direct LLM generation ~500 words, no Tavily search)
    # -------------------------------------------------------------------------
    print("\n[TEST 1] Testing Summary Mode (Direct LLM generation ~500 words)...")
    res_summary = await orchestrator.run_research(
        topic="Advancements in Quantum Computing in 2026",
        report_type="Summary - Short and fast (~2 min)",
        tone="Objective"
    )

    print("Summary Mode Results:")
    print(f"  Mode: {res_summary.get('mode')}")
    print(f"  Report Type: {res_summary.get('report_type')}")
    print(f"  Subqueries: {res_summary.get('subqueries')}")
    print(f"  Sources Count: {len(res_summary.get('sources', []))}")
    word_count = len(res_summary.get('report', '').split())
    print(f"  Report Word Count: {word_count} words")
    agent_names = [a['name'] for a in res_summary.get('agents', [])]
    print(f"  Active Agents: {agent_names}")

    assert len(res_summary.get('subqueries', [])) == 0, "Summary mode must not generate Tavily subqueries"
    assert word_count > 100, f"Expected substantive summary, got {word_count} words"
    assert "WriterAgent" in agent_names, "WriterAgent must be in agent trace"
    print(">>> [TEST 1 PASSED]: Short Summary directly generated by LLM (~500 words) without Tavily!\n")

    # -------------------------------------------------------------------------
    # TEST 2: DEEP RESEARCH MODE (Researched via Tavily API)
    # -------------------------------------------------------------------------
    print("\n[TEST 2] Testing Deep Research Mode (Tavily API Web Intelligence)...")
    res_deep = await orchestrator.run_research(
        topic="Solid state battery commercialization timeline",
        report_type="Deep Research Report",
        tone="Analytical"
    )

    print("Deep Research Results:")
    print(f"  Mode: {res_deep.get('mode')}")
    print(f"  Subqueries Count: {len(res_deep.get('subqueries', []))}")
    print(f"  Sources Count: {len(res_deep.get('sources', []))}")
    deep_agents = [a['name'] for a in res_deep.get('agents', [])]
    print(f"  Active Agents: {deep_agents}")

    assert len(res_deep.get('subqueries', [])) > 0, "Deep research must generate Tavily subqueries"
    assert "ResearchAgent" in deep_agents, "ResearchAgent must query Tavily"
    assert "WriterAgent" in deep_agents, "WriterAgent must synthesize Tavily findings"
    print(">>> [TEST 2 PASSED]: Deep Research properly executes Tavily API search and synthesis!\n")

    # -------------------------------------------------------------------------
    # TEST 3: MULTI AGENTS MODE (Specifically activates ReviewerAgent)
    # -------------------------------------------------------------------------
    print("\n[TEST 3] Testing Multi Agents Mode (Specifically activates ReviewerAgent)...")
    res_multi = await orchestrator.run_research(
        topic="CRISPR gene editing regulatory approval milestones",
        report_type="Multi Agents Report",
        tone="Formal"
    )

    print("Multi Agents Results:")
    print(f"  Mode: {res_multi.get('mode')}")
    print(f"  Review Decision: {res_multi.get('review', {}).get('decision')}")
    print(f"  Factual Grounding: {res_multi.get('review', {}).get('factual_grounding')}")
    multi_agents = [a['name'] for a in res_multi.get('agents', [])]
    print(f"  Active Agents: {multi_agents}")

    assert "ReviewerAgent" in multi_agents, "ReviewerAgent must be explicitly activated in Multi Agents mode"
    assert "WriterAgent" in multi_agents, "WriterAgent must draft the report"
    assert res_multi.get('review') is not None, "ReviewerAgent telemetry must be present"
    print(">>> [TEST 3 PASSED]: Multi Agents mode specifically activates ReviewerAgent audit loop!\n")

    # -------------------------------------------------------------------------
    # TEST 4: DETAILED MODE (Performs and works with ALL 6 agents)
    # -------------------------------------------------------------------------
    print("\n[TEST 4] Testing Detailed Mode (Works with ALL 6 Agents)...")
    res_detailed = await orchestrator.run_research(
        topic="Autonomous humanoid robotics manufacturing scale",
        report_type="Detailed - In depth and longer (~5 min)",
        tone="Objective"
    )

    print("Detailed Mode Results:")
    print(f"  Mode: {res_detailed.get('mode')}")
    detailed_agents = [a['name'] for a in res_detailed.get('agents', [])]
    print(f"  Active Agents: {detailed_agents}")

    expected_all = ["ManagerAgent", "ResearchAgent", "DocumentAgent", "CuratorAgent", "WriterAgent", "ReviewerAgent"]
    for ag in expected_all:
        assert ag in detailed_agents, f"Expected agent {ag} to be active in Detailed mode"

    print(">>> [TEST 4 PASSED]: Detailed mode engages all 6 agents collaboratively!\n")

    print("\n=======================================================")
    print("ALL 4 REPORT TYPE EXECUTION MODES VERIFIED AND PASSING!")
    print("=======================================================\n")

if __name__ == "__main__":
    asyncio.run(test_all_report_types())
