import os
import sys
import json
from pathlib import Path
from typing import List, Dict, Any, Optional, Literal

from dotenv import load_dotenv
from google import genai
from pydantic import BaseModel, Field


# =========================================================
# 1. PROJECT PATH
# =========================================================

project_root = Path(__file__).resolve().parent.parent.parent

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))


# =========================================================
# 2. LOAD ENVIRONMENT VARIABLES
# =========================================================

ENV_PATH = project_root / ".env"
load_dotenv(dotenv_path=ENV_PATH)


# =========================================================
# 3. IMPORT PROJECT CONFIG
# =========================================================

from backend.config import config, get_fallback_chain


# =========================================================
# 4. RESEARCH TASK MODEL
# =========================================================

class ResearchTask(BaseModel):
    """
    Represents one task delegated by the Manager Agent
    to another agent.
    """

    id: str = Field(
        description="Unique ID of the research task"
    )

    agent: Literal[
        "ResearchAgent",
        "DocumentAgent"
    ] = Field(
        description="Agent responsible for completing this task"
    )

    role: str = Field(
        description="Role of the agent for this particular task"
    )

    objective: str = Field(
        description="Specific objective that the agent must accomplish"
    )

    search_query: Optional[str] = Field(
        default=None,
        description=(
            "Main search query if web research is required. "
            "Null for document-only tasks."
        )
    )

    priority: Literal[
        "HIGH",
        "MEDIUM",
        "LOW"
    ] = Field(
        description="Priority of the task"
    )


# =========================================================
# 5. RESEARCH PLAN MODEL
# =========================================================

class ResearchPlan(BaseModel):
    """
    Complete plan generated by the Manager Agent.
    """

    mode: Literal[
        "WEB",
        "DOCUMENT",
        "HYBRID"
    ] = Field(
        description=(
            "WEB = internet research, "
            "DOCUMENT = uploaded document research, "
            "HYBRID = both web and document research"
        )
    )

    reasoning: str = Field(
        description="Short explanation for why this mode was selected"
    )

    tasks: List[ResearchTask] = Field(
        description="Research tasks delegated to other agents"
    )


# =========================================================
# 6. MANAGER AGENT
# =========================================================

class ManagerAgent:
    """
    Manager Agent

    Responsibilities:
    -------------------------------------------------------
    1. Understand the user's research question.
    2. Determine the required research mode.
    3. Decide whether Web RAG, Document RAG, or both
       are required.
    4. Break the question into independent research tasks.
    5. Assign each task to the appropriate agent.

    The Manager DOES NOT perform the actual research.

    It delegates work to:
        - ResearchAgent
        - DocumentAgent
    """

    def __init__(
        self,
        gemini_api_key: str = "",
        tavily_api_key: str = ""
    ):

        # -------------------------------------------------
        # Gemini API key
        # -------------------------------------------------

        self.gemini_api_key = (
            gemini_api_key
            or config.GEMINI_API_KEY
            or os.getenv("GEMINI_API_KEY", "")
        )

        # -------------------------------------------------
        # Tavily API key
        # -------------------------------------------------

        self.tavily_api_key = (
            tavily_api_key
            or config.TAVILY_API_KEY
            or os.getenv("TAVILY_API_KEY", "")
        )

        if not self.gemini_api_key:
            raise ValueError(
                "GEMINI_API_KEY is missing. "
                "Please add it to your .env file."
            )

        # -------------------------------------------------
        # Gemini client
        # -------------------------------------------------

        self.client = genai.Client(
            api_key=self.gemini_api_key
        )

        self.model = getattr(config, "DEFAULT_MODEL", "gemini-3.6-flash")
        self.fallback_models = get_fallback_chain(self.model)

    # =====================================================
    # DETERMINE MODE
    # =====================================================

    def determine_mode(
        self,
        topic: str,
        user_documents: Optional[
            List[Dict[str, Any]]
        ] = None,
        requested_mode: str = "auto"
    ) -> str:
        """
        Determine whether the system should use:

            WEB
            DOCUMENT
            HYBRID

        If the user explicitly specifies a mode,
        respect it.

        If mode is AUTO, Gemini determines the
        appropriate mode.
        """

        if not topic or not topic.strip():
            raise ValueError(
                "Topic/question cannot be empty."
            )

        requested_mode = (
            requested_mode or "auto"
        ).lower().strip()

        # -------------------------------------------------
        # Explicit mode
        # -------------------------------------------------

        if requested_mode in {
            "web",
            "research"
        }:
            return "WEB"

        if requested_mode == "document":
            return "DOCUMENT"

        if requested_mode == "hybrid":
            return "HYBRID"

        # -------------------------------------------------
        # Automatic mode
        # -------------------------------------------------

        has_documents = bool(
            user_documents
            and len(user_documents) > 0
        )

        # If there are no documents, web research is
        # the only available external source.
        if not has_documents:
            return "WEB"

        # -------------------------------------------------
        # Documents exist.
        #
        # We DO NOT automatically choose DOCUMENT.
        #
        # Gemini decides whether the question needs:
        # DOCUMENT or HYBRID.
        # -------------------------------------------------

        prompt = f"""
You are a routing component of a multi-agent
research system.

Determine whether the user's question requires:

WEB:
Information from the internet.

DOCUMENT:
Information from uploaded documents.

HYBRID:
Information from BOTH uploaded documents and
the internet.

Uploaded documents are available.

User question:
{topic}

Rules:

- If the user asks only about the uploaded documents,
  return DOCUMENT.

- If the user asks for current/latest/recent information
  or external information that is not contained in the
  uploaded documents, return HYBRID.

- If the user asks to compare, analyze, or connect
  uploaded documents with external/current information,
  return HYBRID.

Return ONLY one word:
DOCUMENT
or
HYBRID
"""

        result = ""
        for idx, model_name in enumerate(self.fallback_models):
            try:
                response = self.client.models.generate_content(
                    model=model_name,
                    contents=prompt
                )
                if response and response.text:
                    result = response.text.strip().upper()
                    break
            except Exception as e:
                next_model = self.fallback_models[idx + 1] if idx + 1 < len(self.fallback_models) else "default mode"
                print(f"[ManagerAgent] Model {model_name} unavailable: {e}. Redirecting to {next_model}...")
                continue

        if "HYBRID" in result:
            return "HYBRID"

        return "DOCUMENT"

    # =====================================================
    # CREATE RESEARCH PLAN
    # =====================================================

    def create_plan(
        self,
        topic: str,
        mode: str,
        has_documents: bool = False
    ) -> ResearchPlan:
        """
        Ask Gemini to create the actual research plan.

        The Manager decides:

            What needs to be researched?
            Which agent should research it?
            What is the objective?
            What is the priority?
        """

        if not topic or not topic.strip():
            raise ValueError(
                "Topic/question cannot be empty."
            )

        mode = mode.upper().strip()

        if mode not in {
            "WEB",
            "DOCUMENT",
            "HYBRID"
        }:
            raise ValueError(
                f"Invalid research mode: {mode}"
            )

        # -------------------------------------------------
        # Build mode-specific instructions
        # -------------------------------------------------

        if mode == "WEB":

            mode_instruction = """
Only use ResearchAgent tasks.

The ResearchAgent will use:
- QueryPlanner
- Tavily SearchEngine
- SourceProcessor
- WebScraper
- Web RAG

Do NOT create DocumentAgent tasks.
"""

        elif mode == "DOCUMENT":

            mode_instruction = """
Only use DocumentAgent tasks.

The DocumentAgent will use:
- uploaded documents
- document extraction
- document chunking
- embeddings
- Document RAG

Do NOT create ResearchAgent tasks.
Do NOT use web search.
"""

        else:

            mode_instruction = """
Use BOTH ResearchAgent and DocumentAgent.

ResearchAgent handles:
- internet research
- Tavily
- web scraping
- Web RAG

DocumentAgent handles:
- uploaded documents
- Document RAG

Create tasks for both where appropriate.
"""

        # -------------------------------------------------
        # Manager prompt
        # -------------------------------------------------

        prompt = f"""
You are the Manager Agent of a GPT-Researcher-style
multi-agent research system.

Your responsibility is to PLAN and DELEGATE research.

You must NOT perform the research yourself.

USER QUESTION:
{topic}

SELECTED MODE:
{mode}

{mode_instruction}

Create approximately 3 to 5 focused research tasks.

Each task should represent a meaningful piece of work.

Good task examples:

- Research recent technological developments.
- Research major companies and organizations.
- Research current challenges.
- Analyze uploaded document findings.
- Compare information from the uploaded document
  with current external information.

Avoid creating duplicate tasks.

Each task must contain:

1. id
2. agent
3. role
4. objective
5. search_query
6. priority

For DocumentAgent tasks:
search_query should be null.

For ResearchAgent tasks:
search_query should contain a useful initial web query.

The tasks will later be executed by other agents.

Return a structured research plan.
"""

        # -------------------------------------------------
        # Ask Gemini for structured output
        last_error = None
        plan = None

        for idx, model_name in enumerate(self.fallback_models):
            try:
                response = self.client.models.generate_content(
                    model=model_name,
                    contents=prompt,
                    config={
                        "response_mime_type": "application/json",
                        "response_schema": ResearchPlan,
                    },
                )
                if response and response.text:
                    plan = ResearchPlan.model_validate_json(response.text)
                    return plan
            except Exception as e:
                last_error = e
                next_model = self.fallback_models[idx + 1] if idx + 1 < len(self.fallback_models) else "deterministic fallback"
                print(f"[ManagerAgent] Model {model_name} unavailable in create_plan: {e}. Redirecting to {next_model}...")
                continue

        # Deterministic fallback if API models fail
        print(f"[ManagerAgent] Generating deterministic fallback plan for topic '{topic}' (Error: {last_error})")
        tasks = []
        if mode in ("WEB", "HYBRID"):
            tasks.append(ResearchTask(
                id="task_1",
                agent="ResearchAgent",
                role="technology_researcher",
                objective=f"Research recent breakthroughs and state-of-the-art developments on {topic}",
                search_query=topic,
                priority="HIGH"
            ))
            tasks.append(ResearchTask(
                id="task_2",
                agent="ResearchAgent",
                role="industry_analyst",
                objective=f"Investigate commercialization challenges and key industry players for {topic}",
                search_query=f"{topic} commercialization challenges",
                priority="MEDIUM"
            ))
        if mode in ("DOCUMENT", "HYBRID"):
            tasks.append(ResearchTask(
                id="task_doc",
                agent="DocumentAgent",
                role="document_analyst",
                objective=f"Analyze uploaded document content regarding {topic}",
                search_query=None,
                priority="HIGH"
            ))

        return ResearchPlan(
            mode=mode,
            reasoning=f"Generated structured plan for {topic}",
            tasks=tasks
        )

    # =====================================================
    # COMPLETE MANAGER OPERATION
    # =====================================================

    def plan(
        self,
        topic: str,
        user_documents: Optional[
            List[Dict[str, Any]]
        ] = None,
        requested_mode: str = "auto"
    ) -> ResearchPlan:
        """
        Main Manager Agent entry point.

        Workflow:

            User Question
                  ↓
            Determine Mode
                  ↓
            Create Tasks
                  ↓
            Return Plan
        """

        has_documents = bool(
            user_documents
            and len(user_documents) > 0
        )

        # -------------------------------------------------
        # Step 1: determine mode
        # -------------------------------------------------

        mode = self.determine_mode(
            topic=topic,
            user_documents=user_documents,
            requested_mode=requested_mode
        )

        print(
            f"\n[Manager Agent]"
        )

        print(
            f"Selected mode: {mode}"
        )

        # -------------------------------------------------
        # Step 2: create task plan
        # -------------------------------------------------

        research_plan = self.create_plan(
            topic=topic,
            mode=mode,
            has_documents=has_documents
        )

        print(
            f"Generated {len(research_plan.tasks)} tasks."
        )

        # -------------------------------------------------
        # Step 3: display tasks
        # -------------------------------------------------

        for task in research_plan.tasks:

            print(
                f"\n  [{task.id}]"
            )

            print(
                f"  Agent: {task.agent}"
            )

            print(
                f"  Role: {task.role}"
            )

            print(
                f"  Objective: {task.objective}"
            )

            print(
                f"  Priority: {task.priority}"
            )

            if task.search_query:
                print(
                    f"  Search: {task.search_query}"
                )

        return research_plan

    def formulate_plan(
        self,
        topic: str,
        mode: str = "research",
        has_documents: bool = False
    ) -> List[Dict[str, str]]:
        """
        Creates a structured multi-agent execution roadmap.
        Backward-compatible method returning step dictionaries.
        """
        resolved_mode = "DOCUMENT" if mode.lower() == "document" else "WEB"
        plan = self.create_plan(topic=topic, mode=resolved_mode, has_documents=has_documents)
        return [
            {
                "step": str(idx),
                "agent": task.agent,
                "action": task.objective
            }
            for idx, task in enumerate(plan.tasks, start=1)
        ]


# =========================================================
# 7. TEST MANAGER AGENT
# =========================================================

if __name__ == "__main__":

    manager = ManagerAgent()

    print("=" * 60)
    print("GPT-RESEARCHER STYLE MANAGER AGENT")
    print("=" * 60)

    question = input(
        "\nEnter your research question: "
    )

    # -----------------------------------------------------
    # Sample document for testing Document Mode
    # -----------------------------------------------------
    documents = [
        {
            "title": "sample_document.txt",
            "content": """
            Quantum computing uses quantum mechanical phenomena such as superposition
            and entanglement to process information. Quantum algorithms such as Shor's algorithm
            and Grover's algorithm demonstrate exponential speedups for specialized problems.
            Recent benchmarks in 2026 achieved 1.2ms coherence time using topological qubits.
            """
        }
    ]

    plan = manager.plan(
        topic=question,
        user_documents=documents,
        requested_mode="document"
    )

    print("\n" + "=" * 60)
    print("FINAL MANAGER PLAN")
    print("=" * 60)

    print(
        json.dumps(
            plan.model_dump(),
            indent=4
        )
    )